Now properly setting Sentry severity. No longer logging System messages
LuckboxGG/logger-factory pull request #15
Opened 2021-02-22 10:34 UTC by veseo

2021-02-22 15:53 UTC, nikksan commented on src/tests/index.test.ts
> +    ])('should not log %s logLevel', (logLevel) => {
missing type

2021-02-22 15:54 UTC, nikksan commented on src/tests/index.test.ts
> +    ])('should properly translate our logging level %s to Sentry severity - %s', (logLevel: string, severity: Sentry.Severity) => {
it's named logLevel, but it is actually the method name

2021-02-22 16:00 UTC, nikksan commented on src/adapters/SentryLoggerAdapter.ts
> +        return;
Isn't this overriding the logLevel in the constructor?

2021-02-22 16:05 UTC, nikksan commented on src/tests/index.test.ts
> +
Can't leave a discussion, but on: 36 there is ` adapters: [sentryAdapterSettings as ConsoleAdapterSettings],`

2021-02-22 16:07 UTC, nikksan commented on src/tests/index.test.ts
> +
You can avoid all hard casts by adding type to the `sentryAdapterSettings` and `consoleAdapterSettings`

2021-02-23 08:33 UTC, MaDKaTZe requested changes

2021-02-23 08:33 UTC, MaDKaTZe commented on src/adapters/SentryLoggerAdapter.ts
> +  private mapLogLevelToSeverity(logLevel: LogLevels) {
Isn't sentry adapter expected to be able to handle all supported all log levels?

2021-02-23 08:39 UTC, veseo commented on src/adapters/SentryLoggerAdapter.ts
> +  private mapLogLevelToSeverity(logLevel: LogLevels) {
I can add the other levels, except for System, so that it better suits our current needs. In the future, we can change the interface to not pass "minimum log level" but a list of log levels to handle, then we could add System without worrying that it will log system (as they are the highest level) as well. Everyone okay with that plan?

2021-02-23 08:47 UTC, veseo commented on src/adapters/SentryLoggerAdapter.ts
> +        return;
No? The logLevel in the constructor is the minimum loglevel that the adapter would handle, while message.level is the level of the exact message (which we're then trying to map to Sentry.Severity equivalent). Or I misunderstood your question?

2021-02-23 08:52 UTC, MaDKaTZe commented on src/adapters/SentryLoggerAdapter.ts
> +  private mapLogLevelToSeverity(logLevel: LogLevels) {
Resolved.

2021-02-23 08:53 UTC, MaDKaTZe commented on src/tests/index.test.ts
> +    const sentrySupportedLogLevels = [
I think that tests for sentry logger adapter should be updated as well.

2021-02-23 08:59 UTC, MaDKaTZe commented on src/tests/index.test.ts
> +    const sentrySupportedLogLevels = [
Resolved.

2021-02-23 10:52 UTC, merged